/* Generated By:JavaCC: Do not edit this line. EXceLlenSeConstants.java */
package de.hft_stuttgart.cpl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EXceLlenSeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQ = 4;
  /** RegularExpression Id. */
  int FORMATTED = 5;
  /** RegularExpression Id. */
  int FOR = 6;
  /** RegularExpression Id. */
  int FROM = 7;
  /** RegularExpression Id. */
  int TO = 8;
  /** RegularExpression Id. */
  int DO = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int FUNCTION = 11;
  /** RegularExpression Id. */
  int CONCAT = 12;
  /** RegularExpression Id. */
  int ADD = 13;
  /** RegularExpression Id. */
  int SUB = 14;
  /** RegularExpression Id. */
  int MOD = 15;
  /** RegularExpression Id. */
  int DIV = 16;
  /** RegularExpression Id. */
  int MUL = 17;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 18;
  /** RegularExpression Id. */
  int FLOAT_LITERAL_1 = 19;
  /** RegularExpression Id. */
  int FLOAT_LITERAL_2 = 20;
  /** RegularExpression Id. */
  int FLOAT_LITERAL_3 = 21;
  /** RegularExpression Id. */
  int STRING_LITERAL = 22;
  /** RegularExpression Id. */
  int TIMESTAMP_LITERAL = 23;
  /** RegularExpression Id. */
  int VARIABLE = 24;
  /** RegularExpression Id. */
  int COMP_OP = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"=\"",
    "\"FORMATTED\"",
    "\"for\"",
    "\"from\"",
    "\"to\"",
    "\"do\"",
    "\"end\"",
    "\"func\"",
    "\"&\"",
    "\"+\"",
    "\"-\"",
    "\"%\"",
    "\"/\"",
    "\"*\"",
    "<DECIMAL_LITERAL>",
    "<FLOAT_LITERAL_1>",
    "<FLOAT_LITERAL_2>",
    "<FLOAT_LITERAL_3>",
    "<STRING_LITERAL>",
    "<TIMESTAMP_LITERAL>",
    "<VARIABLE>",
    "<COMP_OP>",
    "\"C\"",
    "\"R\"",
    "\"(\"",
    "\")\"",
  };

}
